name: 'PickHaxe - Build Project'
description: 'Runs "pickhaxe build" and "pickhaxe make"'

inputs:
  os:
    description: 'Docker image used to run this build'
    required: true
    default: ubuntu-latest
  haxe:
    description: 'Haxe version used to run this build'
    required: true
    default: 4.3.0
  sample:
    description: 'The name of the sample to build'
    required: true
  mcloader:
    description: 'The Minecraft mod loader to target'
    required: true
  mcversion:
    description: 'The Minecraft version to target'
    required: true
  pickhaxe:
    description: 'The PickHaxe version to install'
    required: true
    default: '@git:https://github.com/EliteMasterEric/PickHaxe#develop' # Latest development version

runs:
  using: "composite"
  steps:
    - name: "Print Inputs"
      shell: bash
      run: |
        echo "os: ${{inputs.os}}"
        echo "haxe: ${{inputs.haxe}}"
        echo "sample: ${{inputs.sample}}"
        echo "mcloader: ${{inputs.mcloader}}"
        echo "mcversion: ${{inputs.mcversion}}"
        echo "pickhaxe: ${{inputs.pickhaxe}}"
    - name: "Setup: Java 17"
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: "Setup: Haxe ${{ inputs.haxe }} and PickHaxe (${{(inputs.pickhaxe == '') && 'Release' || 'Develop'}})"
      uses: vegardit/haxe-reusable-workflows/.github/actions/setup-haxe@v1
      with:
        haxe-version: ${{ inputs.haxe }}
        haxe-libs: |
          haxelib@git:https://github.com/HaxeFoundation/haxelib#development
          hxjava
          pickhaxe${{ inputs.pickhaxe }}
    - name: "Build: pickhaxe build && pickhaxe make"
      # Using Mojang mappings because they're more up-to-date (they have fewer docs but we don't need them)
      shell: bash
      run: |
        cd ./${{inputs.sample}}
        haxelib run pickhaxe build ${{inputs.mcloader}} ${{inputs.mcversion}} --mappings mojang
        haxelib run pickhaxe make ${{inputs.mcloader}} ${{inputs.mcversion}} --mappings mojang