name: Build Samples
on:
  workflow_dispatch: # We can run this workflow manually
    inputs:
  push: # We run this workflow whenever we push (but only if a relevant file changed)
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.editorconfig'
    - '.git*'
    - '.github/*.yml'
    - 'tools'

defaults:
  run:
    shell: bash

# The jobs to perform; these run in parallel.
jobs:
  # Perform a PickHaxe build and make.
  # The task should fail if Gradle fails.
  build:
    name: Build ${{env.pickhaxe}} (${{matrix.sample}} ${{matrix.mcloader}} ${{matrix.mcversion}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        haxe:
        - 4.3.0
        sample:
        - madeinhaxe
        mcloader:
        - fabric
        mcversion:
        - 1.19.3
        pickhaxe:
        - ''
        - '@git:https://github.com/EliteMasterEric/PickHaxe#develop'
    env:
      pickhaxe: ${{(matrix.pickhaxe == '') && 'Release' || 'Develop'}}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
    - name: "Install: Haxe ${{ matrix.haxe }} and PickHaxe (${{env.pickhaxe}})"
      uses: vegardit/haxe-reusable-workflows/.github/actions/setup-haxe@v1
      with:
        haxe-version: ${{ matrix.haxe }}
        haxe-libs: |
          PickHaxe${{ matrix.pickhaxe }}
    - name: pickhaxe build && pickhaxe make
      run: |
        haxelib run pickhaxe build ${{matrix.mcloader}} ${{matrix.mcversion}}
        haxelib run pickhaxe make ${{matrix.mcloader}} ${{matrix.mcversion}}
