name: Build Samples
on:
  workflow_dispatch: # We can run this workflow manually
    inputs:
  push: # We run this workflow whenever we push (but only if a relevant file changed)
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.editorconfig'
    - '.git*'
    - '.github/*.yml'
    - 'tools'

defaults:
  run:
    shell: bash

# The jobs to perform; these run in parallel.
jobs:
  # Perform a PickHaxe build and make.
  # The task should fail if Gradle fails.
  build:
    name: Build ${{(matrix.pickhaxe == '') && 'Release' || 'Develop'}} (${{matrix.sample}} ${{matrix.mcloader}} ${{matrix.mcversion}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        haxe:
        - 4.3.0
        sample:
        - madeinhaxe
        mcloader:
        - fabric
        - forge
        mcversion:
        - 1.19.3
        pickhaxe:
        - ''
        - '@git:https://github.com/EliteMasterEric/PickHaxe#develop'
    env:
      pickhaxe: ${{(matrix.pickhaxe == '') && 'Release' || 'Develop'}}
    steps:
    - name: "Setup: Git Checkout"
      uses: actions/checkout@v3
    - name: "Setup: Java 17"
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: "Setup: Haxe ${{ matrix.haxe }} and PickHaxe (${{env.pickhaxe}})"
      uses: vegardit/haxe-reusable-workflows/.github/actions/setup-haxe@v1
      with:
        haxe-version: ${{ matrix.haxe }}
        haxe-libs: |
          pickhaxe${{ matrix.pickhaxe }}
    - name: "Build: pickhaxe build && pickhaxe make"
      run: |
        cd ./${{matrix.sample}}
        haxelib run pickhaxe build ${{matrix.mcloader}} ${{matrix.mcversion}} --verbose
        haxelib run pickhaxe make ${{matrix.mcloader}} ${{matrix.mcversion}} --verbose
    - name: "Cleanup: Upload Artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.sample}}-${{matrix.mcloader}}-${{matrix.mcversion}}_${{(matrix.pickhaxe == '') && 'release' || 'develop'}}
        path: ./${{matrix.sample}}/build/${{matrix.mcloader}}/${{matrix.mcversion}}/*.jar