name: Build All
on:
  workflow_dispatch: # We can run this workflow manually
    inputs:
  push: # We run this workflow whenever we push (but only if a relevant file changed)
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.editorconfig'
    - '.git*'
    - '.github/*.yml'
    - 'tools'

defaults:
  run:
    shell: bash

# The jobs to perform; these run in parallel.
jobs:
  # Perform a PickHaxe build and make.
  # The task should fail if Gradle fails.
  build:
    name: ${{(matrix.pickhaxe == 'haxelib') && 'Release' || 'Develop'}} (${{matrix.sample}} ${{matrix.mcloader}} ${{matrix.mcversion}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        include:
          - sample: madeinhaxe/fabric-1.19.4
            mcloader: fabric
            mcversion: 1.19.4
          - sample: madeinhaxe/fabric-1.20.6
            mcloader: fabric
            mcversion: 1.20.6
          - sample: madeinhaxe/forge-1.19.4
            mcloader: forge
            mcversion: 1.19.4
        pickhaxe:
        - 'haxelib' # Current HaxeLib version
        - 'git' # Latest development version
    env:
      pickhaxe: ${{(matrix.pickhaxe == 'haxelib') && 'Release' || 'Develop'}}
    steps:
    - name: "Setup: Git Checkout"
      uses: actions/checkout@v3
    - name: "Build: pickhaxe build"
      uses: ./.github/actions/build-pickhaxe-sample
      with:
        os: ${{matrix.os}}
        sample: ${{matrix.sample}}
        mcloader: ${{matrix.mcloader}}
        mcversion: ${{matrix.mcversion}}
        pickhaxe: ${{matrix.pickhaxe}}
    - name: "Cleanup: Upload Artifacts"
      if: env.ACT != 'true' # https://github.com/nektos/act#skipping-steps
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.sample}}-${{matrix.mcloader}}-${{matrix.mcversion}}_${{(matrix.pickhaxe == 'haxelib') && 'release' || 'develop'}}
        path: ./${{matrix.sample}}/build/${{matrix.mcloader}}/${{matrix.mcversion}}/*.jar
    - name: "Cleanup: Update Badge (Success)"
      if: ${{ success() }}
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: build-${{matrix.sample}}-${{matrix.mcloader}}-${{matrix.mcversion}}_${{(matrix.pickhaxe == 'haxelib') && 'release' || 'develop'}}
        LABEL: ${{matrix.mcloader}} v${{matrix.mcversion}}
        ICON: 'github'
        STATUS: 'passing'
        COLOR: 'green'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "Cleanup: Update Badge (Failure)"
      if: ${{ failure() }}
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: build-${{matrix.sample}}-${{matrix.mcloader}}-${{matrix.mcversion}}_${{(matrix.pickhaxe == 'haxelib') && 'release' || 'develop'}}
        LABEL: ${{matrix.mcloader}} v${{matrix.mcversion}}
        ICON: 'github'
        STATUS: 'failing'
        COLOR: 'red'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}