name: Build Target
on:
  workflow_dispatch: # We can run this workflow manually
    inputs:
      os:
        description: 'Docker image'
        required: true
        default: ubuntu-latest
        type: string
      sample:
        description: 'Sample to build'
        required: true
        default: 'madeinhaxe'
        type: choice
        options:
          - madeinhaxe
          - obsidianarmor
      mcloader:
        description: 'Minecraft modloader'
        required: true
        default: 'fabric'
        type: choice
        options:
          - fabric
          - forge
      mcversion:
        description: 'Minecraft version'
        required: true
        default: 'latest'
        type: string
      pickhaxe:
        description: 'PickHaxe version'
        required: true
        default: 'git'
        type: choice
        options:
          - 'haxelib'
          - 'git'

defaults:
  run:
    shell: bash

# The jobs to perform; these run in parallel.
jobs:
  # Perform a PickHaxe build and make.
  # The task should fail if Gradle fails.
  build:
    name: ${{(inputs.pickhaxe == 'haxelib') && 'Release' || 'Develop'}} (${{inputs.sample}} ${{inputs.mcloader}} ${{inputs.mcversion}})
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
    env:
      pickhaxe: ${{(inputs.pickhaxe == 'haxelib') && 'Release' || 'Develop'}}
    steps:
    - name: "Setup: Git Checkout"
      uses: actions/checkout@v3
    - name: "Build: pickhaxe build && pickhaxe make"
      uses: ./.github/actions/build-pickhaxe-sample
      with:
        os: ${{inputs.os}}
        sample: ${{inputs.sample}}
        mcloader: ${{inputs.mcloader}}
        mcversion: ${{inputs.mcversion}}
        pickhaxe: ${{inputs.pickhaxe}}
    - name: "Cleanup: Upload Artifacts"
      if: env.ACT != 'true' # https://github.com/nektos/act#skipping-steps
      uses: actions/upload-artifact@v3
      with:
        name: ${{inputs.sample}}-${{inputs.mcloader}}-${{inputs.mcversion}}_${{(inputs.pickhaxe == 'haxelib') && 'release' || 'develop'}}
        path: ./${{inputs.sample}}/build/${{inputs.mcloader}}/${{inputs.mcversion}}/*.jar
    - name: "Cleanup: Update Badge (Success)"
      if: ${{ success() }}
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: build-${{inputs.sample}}-${{inputs.mcloader}}-${{inputs.mcversion}}_${{(inputs.pickhaxe == 'haxelib') && 'release' || 'develop'}}
        LABEL: ${{inputs.mcloader}} v${{inputs.mcversion}}
        ICON: 'github'
        STATUS: 'passing'
        COLOR: 'green'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "Cleanup: Update Badge (Failure)"
      if: ${{ failure() }}
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: build-${{inputs.sample}}-${{inputs.mcloader}}-${{inputs.mcversion}}_${{(inputs.pickhaxe == 'haxelib') && 'release' || 'develop'}}
        LABEL: ${{inputs.mcloader}} v${{inputs.mcversion}}
        ICON: 'github'
        STATUS: 'failing'
        COLOR: 'red'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
